server:
  port: 8080
spring:
  application:
    name: "CollaboApp"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:mysql://localhost:3307/collabo-db
    username: root
    password: admin
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: admin


management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
    springframework:
      security: DEBUG


